### PR TITLE
Skip installation if the version is already installed

### PR DESCRIPTION
**Pull request by kdisneur**

### CODE REVIEW

**Comment by HashNuke** [comment]
@kdisneur default exit code is zero. This change isn't required. Just removing the "exit 1" was sufficient.

**Comment by HashNuke** [comment]
Sorry just read the code. It looks like this exit is required. I'll re-read it when I get back to desk again (in bed now)

**Comment by HashNuke** [comment]
@kdisneur Thank you. Merged ~!

**Comment by kdisneur** [comment]
:+1: thanks - with this version my CI build passes and a rebuild passes also :)

**Pull request merged**
